```yaml
# .readthedocs.yaml
# Read the Docs configuration file for RestAPILibrary
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"  # Python 3.10 as per setup.py compatibility (3.7+ supported)

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false  # Allow build to pass even with warnings

# Python configuration
python:
  install:
    - requirements: requirements.txt  # Install dependencies
    - method: pip
      path: .  # Install the package itself
      extra_requirements:
        - redis  # Include optional redis dependency
        - dev    # Include development dependencies (pytest, black, etc.)

# Optionally specify formats (default is HTML, PDF, and ePub)
formats:
  - htmlzip
  - pdf
```